### ISSUE TITLE
Support @sentry/node for FastBoot

### ISSUE THREAD

**Issue by mhluska** [damiencaselli/ember-cli-sentry#137] opened 2018-09-01 16:16 UTC
Any plans to use `@sentry/node` to get error reporting working in FastBoot? I was finding this library just drops exceptions in the FastBoot environment but some errors only arise in that environment.

See https://github.com/getsentry/sentry-javascript/tree/master/packages/node

**Comment by Turbo87** [comment] 2018-09-05 08:56
@mhluska in the long term that would be nice to have, yes. do you have time to work on that?

**Comment by Turbo87** [comment] 2018-09-26 09:59
I'll close this as a duplicate of #77

**Closed by Turbo87** 2018-09-26 09:59 UTC
Labels: enhancement
